### ISSUE TITLE
Working on a new feature for this repos. Not an issue.

### ISSUE THREAD

**Issue by DefaultO** [playingoDEERUX/growbrewproxy#36]
Basically I am working on a Pathfinding System that originally was meant to use with the auto farmers. But once it is done, by pushing more and more updates toward it, it could be used for basically everything. Parkour, for example. Can you give me the player action packets for moving around (_left & right_), jump & punching at x,y (_i will implement calculations myself to avoid bans / impossible reach_) @playingoDEERUX ? Can't seem to find any example in the Proxy Client. Have found punch although inside the Autofarm Method inside MainForm's code.

                        TankPacket tkPt = new TankPacket();
                        tkPt.PunchX = x;
                        tkPt.PunchY = y;
                        tkPt.X = messageHandler.worldMap.player.X;
                        tkPt.Y = messageHandler.worldMap.player.Y;
                        tkPt.ExtDataMask &= ~0x04;
                        tkPt.ExtDataMask &= ~0x40;
                        tkPt.ExtDataMask &= ~0x10000;
                        tkPt.NetID = -1;

                        lock (realPeer)
                        {
                            lock (proxyPeer)
                            {
                                messageHandler.packetSender.SendPacketRaw(4, tkPt.PackForSendingRaw(), realPeer);
                                tkPt.NetID = -1;
                                tkPt.PacketType = 3;
                                tkPt.ExtDataMask = 0;
                                messageHandler.packetSender.SendPacketRaw(4, tkPt.PackForSendingRaw(), realPeer);
                            }
                        }

Currently having this as of now:
_Have to apparently do the loop a bit different, since the tiles don't seem to be sorted (from one corner to another)_

    public enum TileDescriptor
    {
        Air = 1,    // Nothing / Blank
        Switch = 2  // Dragon Gate / Fissure - need to be checked if closed or not
    }

    public class Pathfinding
    {
        private Tile[] tiles;
        int[,] array;

        public void getEmptySpace()
        {
            World currentWorld = MainForm.messageHandler.worldMap;

            if (currentWorld.tiles.Length > 0 || currentWorld.tiles != null)
                tiles = currentWorld.tiles;

            // 2D Map that we will use to assign walkable space.
            // Matrix of currentWorld.width (100) * currentWorld.height (60).
            // Imagine it as minesweeper once the whole process is done.
            array = new int[currentWorld.width, currentWorld.height];

            // TODO: get whole World Data and loop through all blocks/coordinates and check if it's a solid block
            List<string> tileIds = new List<string>();
            foreach(Tile tile in tiles)
            {
                /*if (!tileIds.Contains(tile.fg.ToString()))
                {
                    tileIds.Add(tile.fg.ToString());
                }*/
                
                switch (tile.fg)
                {
                    // Air
                    case 0:
                        array[tile.x, tile.y] = (int)TileDescriptor.Air;
                        break;
                    // Fissure
                    case 5032:
                        array[tile.x, tile.y] = (int)TileDescriptor.Switch;
                        break;
                }
            }
            /*foreach(string listItem in tileIds)
            {
                Console.WriteLine(listItem);
            }
            Console.WriteLine(tileIds.Count);*/

            /*
            Block ID List of CHANDELIERAUTOFARM1
            1684 - Path Marker
            0 - Air
            2 - Dirt
            5032 - Fissure
            546 - Blue Portal
            7164 - Red House Entrance
            5716 - Weather Mashine (St. Patricks Day)
            1276 - Punch Jammer
            6 - White Door
            2946 - Display Block
            226 - Signal Jammer
            242 - World Lock
            8 - Bedrock
            3760 - Data Bedrock ???
            */
            // TODO: make a new Map Structure for those passable blocks/coordinates
        }

        private void gotoClosestFarmable()
        {
            // TODO: pathfind through all possible paths inside getEmptySpace()
            // TODO: make use of walk, jump packets to go to the target
        }

        // TODO: other logic
    }

**Comment by playingoDEERUX** [comment]
Packet Type 0 is used for movement request, it is also the same packet type being broadcasted to all clients in a world to let other players know about your movement after validation is passed.

What you wanna do is send that packet multiple times with not too big X/Y difference to prevent autoban depending on how far the path is.

Then you should be able to securely break the tile (by "secure", I mean most likely in a way to not get autobanned and/or getting your break/place request rejected) with the Packet Type 3 packet.

So to move, you should set the Packet Type to 0, X/Y always a bit closer to the tile you wanna reach (via a loop you ensure you reached close enough to that tile by constantly making the X/Y pos getting more closer and resending the packet)
And you want to keep XSpeed and YSpeed in mind, if they are 0 or very low and it does not keep up with the amount of X/Y you have changed, it might seem suspicious to the server and you may get banned.

And at least, maybe keep track of the "ExtDataMask" value because the server uses its bits (32 bit int) to determine what type of 'movement state' your character is currently having active, it could be currently being hit by lava, walking left/right (I think they just used a single bit set for that whether its off or on at a certain position, don't remember them all by my head) or whether the character is having the jump animation/sprite active etc...

That's basically it.
