### ISSUE TITLE
is there anyway open multiple growtopias

### ISSUE THREAD

**Issue by vietor55** [playingoDEERUX/growbrewproxy#43]
Is there anyway open multiple growtopias?
i need it for autofarm :)
Thanks!

**Comment by DefaultO** [comment]
@vietor55 it actually shouldn't be hard to manage to do it. Maybe it's even enough to have multiple instances of Growtopia opened at once. Since the proxy server isn't interested in the "Growtopia" process, but just gets all the traffic. The only problem might be, it, sending back the response to the false client (shouldn't technically happen tho).

For Multiboxing you have to kill/close the mutant of Growtopia (there are 2 similiar named ones with "Growtopia" in it when you look at the handles of the game, those are the right ones, but I guess, only one of them is enough too). You have to do it while the game is frozen, if you haven't patched memory yet.

Here's a code example on how to do it:
https://github.com/Blacklock/gtautofarmer/blob/e63439e84a7bb971d46816d07448204fe3b0c55c/Autofarmer/Autofarm.cs#L269

Since I've heard Ubisoft (Growtopia) Servers don't accept too many Clients from the same IP, you will have to add Proxy Support to the growbrewproxy project. And then get some premium proxies using a paid/cracked proxy scraper. At least that's how my bots do run.

**Comment by playingoDEERUX** [comment]
Growbrew Proxy Extreme Edition has integrated multi/crossbotting allowing you to use roughly 60 bots at a single time, bypassing the IP limit of Growtopia and it mirrors the packets sent by your GT client to all other subclients. Basically reinventing multiboxing.

You can purchase it from me for 15$, discord: DEERUX#1551.
2 copies have been sold already.
